import Link from 'next/link'
import { Nunito } from 'next/font/google'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Terms of Service | Bolo Buddy',
  description: 'Terms of Service for Bolo Buddy.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FFF8F0]">
      <div className="mx-auto max-w-2xl px-5 py-12">
        <Link
          href="/bolo-buddy"
          className="mb-6 inline-block text-sm text-gray-600 hover:text-gray-900"
        >
          ← Wapas jao
        </Link>
        <h1
          className={`${nunito.className} text-3xl font-bold text-[#7B2FBE]`}
        >
          Terms of Service
        </h1>
        <p className="mb-10 text-sm text-gray-400">Last updated: March 2026</p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Acceptance of Terms
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          By using Bolo Buddy, you agree to these terms. If you do not agree,
          please do not use the app. These terms apply to all users including
          parents, guardians, and any person accessing the service on behalf of
          a child.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Who Can Use Bolo Buddy
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          Bolo Buddy is intended for use by parents and guardians for children
          aged 2–10. You must be at least 18 years old to create an account. By
          creating an account you confirm that you are the parent or legal
          guardian of the child whose profile you create.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Free and Premium Plans
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          Free accounts may generate up to 3 stories per month. Premium
          accounts at ₹299/month receive unlimited story generation. Pricing may
          change with 30 days notice. Payments are processed securely via
          Razorpay. Subscriptions can be cancelled at any time — no refunds for
          partial months.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Acceptable Use
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          You agree not to: attempt to reverse-engineer or scrape the service,
          resell or redistribute generated stories commercially, use the service
          to generate harmful or inappropriate content, create multiple free
          accounts to circumvent story limits.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Intellectual Property
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          Stories generated by Bolo Buddy are for personal, non-commercial use
          by your family. Bolo Buddy and the Pari character are trademarks of
          Growing With Kid. You may not use our branding without written
          permission.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Termination
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          We reserve the right to suspend or terminate accounts that violate
          these terms. You may delete your account at any time by{' '}
          <a
            href="mailto:growingwithkid@gmail.com"
            className="text-[#FF6B35] underline"
          >
            contacting us
          </a>
          .
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Limitation of Liability
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          Bolo Buddy is provided &quot;as is.&quot; We are not liable for any
          indirect or consequential damages arising from use of the service.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Governing Law
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          These terms are governed by the laws of India. Any disputes shall be
          subject to the jurisdiction of courts in Faridabad, Haryana.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-bold text-[#2D2D2D]">
          Contact
        </h2>
        <p className="text-base leading-relaxed text-gray-600">
          For questions about these terms:{' '}
          <a
            href="mailto:growingwithkid@gmail.com"
            className="text-[#FF6B35] underline"
          >
            growingwithkid@gmail.com
          </a>
        </p>
      </div>
    </div>
  )
}
